//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Talent
    {
        public int PKTalent_ID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Required")]
        public string HomePhoneNum { get; set; }
        [Required(ErrorMessage = "Required")]
        public string CellPhoneNum { get; set; }
        [Required(ErrorMessage = "Required")]
        public string BirthDate { get; set; }
        [Required(ErrorMessage = "Required")]
        public string Gender { get; set; }
        [Required(ErrorMessage = "Required")]
        public double Weight { get; set; }
        [Required(ErrorMessage = "Required")]
        public double Height { get; set; }
        [Required(ErrorMessage = "Required")]
        public string EyeColor { get; set; }
        [Required(ErrorMessage = "Required")]
        public string HairColor { get; set; }
        [Required(ErrorMessage = "Required")]
        public string UnionStatus { get; set; }
        [Required(ErrorMessage = "Required")]
        public double SIN { get; set; }

        public int LoginLogin_ID { get; set; }
        [Required(ErrorMessage = "Required")]
        public string EthinicOrigin { get; set; }
        [Required(ErrorMessage = "Required")]
        public string CarMake { get; set; }
        [Required(ErrorMessage = "Required")]
        public string CarModel { get; set; }
        [Required(ErrorMessage = "Required")]
        public string CarYear { get; set; }
        [Required(ErrorMessage = "Required")]
        public string CarColor { get; set; }

        public string ResetPaswordCode { get; set; }
        public string ImagePath { get; set; }
        [Required(ErrorMessage = "Required")]
        public string PostalCode { get; set; }
        [Required(ErrorMessage = "Required")]
        public string City { get; set; }

        public virtual Login Login { get; set; }
    }
}
